// Generated by scripts/generate-reference-frontend.mjs. Do not edit.
import type {
  AcceptOfferOutcomeResponse,
  DeclineOfferOutcomeResponse,
  OfferResponse,
  RegistrationDetailsInput,
  RegistrationOutcomeResponse,
  WaitlistDetailsInput,
  WaitlistOutcomeResponse,
  WorkshopCollectionResponse,
  WorkshopDetailResponse
} from "./generated/contracts";
import { realization } from "./generated/realization";

const byId = new Map(realization.operations.map((operation) => [operation.operationId, operation]));
const operation = (id: string) => {
  const value = byId.get(id as typeof realization.operations[number]["operationId"]);
  if (!value) throw new Error(`Missing generated API operation ${id}`);
  return value;
};
const pathFor = (id: string, parameters: Record<string, string> = {}) =>
  operation(id).path.replace(/\{([^}]+)\}/g, (_, name: string) => encodeURIComponent(parameters[name] ?? ""));
const token = () => localStorage.getItem("referenceAuthToken") ?? "token-alex";

async function request<T>(id: string, parameters?: Record<string, string>, body?: unknown): Promise<T> {
  const definition = operation(id);
  const response = await fetch(pathFor(id, parameters), {
    method: definition.method,
    headers: {
      ...(definition.commandRef || id === "getOffer" ? { authorization: `Bearer ${token()}` } : {}),
      ...(body ? { "content-type": "application/json" } : {})
    },
    ...(body ? { body: JSON.stringify(body) } : {})
  });
  const payload = await response.json();
  if (!response.ok) throw new Error(payload.error ?? `Request failed with status ${response.status}`);
  return payload as T;
}

export const api = {
  listWorkshops: () => request<WorkshopCollectionResponse>("listWorkshops"),
  getWorkshop: (workshopId: string) => request<WorkshopDetailResponse>("getWorkshop", { workshopId }),
  confirmRegistration: (workshopId: string, body: RegistrationDetailsInput) =>
    request<RegistrationOutcomeResponse>("confirmRegistration", { workshopId }, body),
  joinWaitlist: (workshopId: string, body: WaitlistDetailsInput) =>
    request<WaitlistOutcomeResponse>("joinWaitlist", { workshopId }, body),
  getOffer: (offerId: string) => request<OfferResponse>("getOffer", { offerId }),
  acceptOffer: (offerId: string) => request<AcceptOfferOutcomeResponse>("acceptOffer", { offerId }),
  declineOffer: (offerId: string) => request<DeclineOfferOutcomeResponse>("declineOffer", { offerId })
};
